/* This file is part of the Navitab project. See the README and LICENSE for details. */

#pragma once

#include <cassert>
#include <stdint.h>
#include <vector>
#include "navitab/window.h"

namespace navitab {

// TextureBuffer objects contain RGBA pixel data that has been generated by
// some part of the Navitab core, and is then given to the window interface
// to be rendered. The window interface creates a TextureBuffer for each of
// the window parts, sized to accomodate the largest area that the window
// part can be expanded to. The actual width and height are adapted when the
// pixel data is delivered (see the PartPainter interface).

class TextureBuffer : public MaxSizeImageBuffer
{
public:
    TextureBuffer(int mw, int mh) : MaxSizeImageBuffer(mw, mh), isTexRegistered(false) { }
    ~TextureBuffer() = default;

    void Resize(int w, int h) override { MaxSizeImageBuffer::Resize(w, h); isTexRegistered = false; }
    bool NeedsRegistration() { auto nr = !isTexRegistered; isTexRegistered = true; return nr; }

private:
    bool isTexRegistered;
};

} // namespace navitab
